spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.33.48:3306/materials?characterEncoding=UTF-8&useSSL=false
    username: materials
    password: Materials@123
server:
  port: 8889
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
logging:
  level:
    web: DEBUG